CREATE TABLE IF NOT EXISTS wfigs (
    OBJECTID INTEGER,
    SourceOID INTEGER,
    ABCDMisc TEXT,
    ADSPermissionState TEXT,
    ContainmentDateTime TIMESTAMP,
    ControlDateTime TIMESTAMP,
    CreatedBySystem TEXT,
    IncidentSize DOUBLE PRECISION,
    DiscoveryAcres DOUBLE PRECISION,
    DispatchCenterID TEXT,
    EstimatedCostToDate DOUBLE PRECISION,
    FinalAcres DOUBLE PRECISION,
    FinalFireReportApprovedByTitle TEXT,
    FinalFireReportApprovedByUnit TEXT,
    FinalFireReportApprovedDate TIMESTAMP,
    FireBehaviorGeneral TEXT,
    FireBehaviorGeneral1 TEXT,
    FireBehaviorGeneral2 TEXT,
    FireBehaviorGeneral3 TEXT,
    FireCause TEXT,
    FireCauseGeneral TEXT,
    FireCauseSpecific TEXT,
    FireCode TEXT,
    FireDepartmentID TEXT,
    FireDiscoveryDateTime TIMESTAMP,
    FireMgmtComplexity TEXT,
    FireOutDateTime TIMESTAMP,
    FireStrategyConfinePercent INTEGER,
    FireStrategyFullSuppPercent INTEGER,
    FireStrategyMonitorPercent INTEGER,
    FireStrategyPointZonePercent INTEGER,
    FSJobCode TEXT,
    FSOverrideCode TEXT,
    GACC TEXT,
    ICS209ReportDateTime TIMESTAMP,
    ICS209ReportForTimePeriodFrom TIMESTAMP,
    ICS209ReportForTimePeriodTo TIMESTAMP,
    ICS209ReportStatus TEXT,
    IncidentManagementOrganization TEXT,
    IncidentName TEXT,
    IncidentShortDescription TEXT,
    IncidentTypeCategory TEXT,
    IncidentTypeKind TEXT,
    InitialLatitude DOUBLE PRECISION,
    InitialLongitude DOUBLE PRECISION,
    InitialResponseAcres DOUBLE PRECISION,
    InitialResponseDateTime TIMESTAMP,
    IrwinID TEXT,
    IsFireCauseInvestigated INTEGER,
    IsFireCodeRequested INTEGER,
    IsFSAssisted INTEGER,
    IsMultiJurisdictional INTEGER,
    IsQuarantined INTEGER,
    IsReimbursable INTEGER,
    IsTrespass INTEGER,
    IsUnifiedCommand INTEGER,
    IsValid INTEGER,
    LocalIncidentIdentifier TEXT,
    ModifiedBySystem TEXT,
    PercentContained INTEGER,
    PercentPerimeterToBeContained INTEGER,
    POOCity TEXT,
    POOCounty TEXT,
    POODispatchCenterID TEXT,
    POOFips TEXT,
    POOJurisdictionalAgency TEXT,
    POOJurisdictionalUnit TEXT,
    POOJurisdictionalUnitParentUnit TEXT,
    POOLandownerCategory TEXT,
    POOLandownerKind TEXT,
    POOLegalDescPrincipalMeridian TEXT,
    POOLegalDescQtr TEXT,
    POOLegalDescQtrQtr TEXT,
    POOLegalDescRange TEXT,
    POOLegalDescSection TEXT,
    POOLegalDescTownship TEXT,
    POOPredictiveServiceAreaID TEXT,
    POOProtectingAgency TEXT,
    POOProtectingUnit TEXT,
    POOState TEXT,
    PredominantFuelGroup TEXT,
    PredominantFuelModel TEXT,
    PrimaryFuelModel TEXT,
    SecondaryFuelModel TEXT,
    TotalIncidentPersonnel INTEGER,
    UniqueFireIdentifier TEXT,
    WFDSSDecisionStatus TEXT,
    EstimatedFinalCost DOUBLE PRECISION,
    OrganizationalAssessment TEXT,
    StrategicDecisionPublishDate TIMESTAMP,
    CreatedOnDateTime_dt TIMESTAMP,
    ModifiedOnDateTime_dt TIMESTAMP,
    IsCpxChild INTEGER,
    CpxName TEXT,
    CpxID TEXT,
    SourceGlobalID TEXT,
    GlobalID TEXT,
    IncidentComplexityLevel TEXT,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION
);