CREATE TABLE wfigs (
    OBJECTID TEXT,  -- todo: convert to INTEGER,
    SourceOID TEXT,  -- todo: convert to INTEGER,
    ABCDMisc TEXT,
    ADSPermissionState TEXT,
    ContainmentDateTime TEXT,  -- todo: convert to timestamp,
    ControlDateTime TEXT,  -- todo: convert to timestamp,
    CreatedBySystem TEXT,
    IncidentSize TEXT,  -- todo: convert to DOUBLE PRECISION,
    DiscoveryAcres TEXT,  -- todo: convert to DOUBLE PRECISION,
    DispatchCenterID TEXT,
    EstimatedCostToDate TEXT,  -- todo: convert to DOUBLE PRECISION,
    FinalAcres TEXT,  -- todo: convert to DOUBLE PRECISION,
    FinalFireReportApprovedByTitle TEXT,
    FinalFireReportApprovedByUnit TEXT,
    FinalFireReportApprovedDate TEXT,  -- todo: convert to timestamp,
    FireBehaviorGeneral TEXT,
    FireBehaviorGeneral1 TEXT,
    FireBehaviorGeneral2 TEXT,
    FireBehaviorGeneral3 TEXT,
    FireCause TEXT,
    FireCauseGeneral TEXT,
    FireCauseSpecific TEXT,
    FireCode TEXT,
    FireDepartmentID TEXT,
    FireDiscoveryDateTime TEXT,  -- todo: convert to timestamp,
    FireMgmtComplexity TEXT,
    FireOutDateTime TEXT,  -- todo: convert to timestamp,
    FireStrategyConfinePercent TEXT,  -- todo: convert to INTEGER,
    FireStrategyFullSuppPercent TEXT,  -- todo: convert to INTEGER,
    FireStrategyMonitorPercent TEXT,  -- todo: convert to INTEGER,
    FireStrategyPointZonePercent TEXT,  -- todo: convert to INTEGER,
    FSJobCode TEXT,
    FSOverrideCode TEXT,
    GACC TEXT,
    ICS209ReportDateTime TEXT,  -- todo: convert to timestamp,
    ICS209ReportForTimePeriodFrom TEXT,  -- todo: convert to timestamp,
    ICS209ReportForTimePeriodTo TEXT,  -- todo: convert to timestamp,
    ICS209ReportStatus TEXT,
    IncidentManagementOrganization TEXT,
    IncidentName TEXT,
    IncidentShortDescription TEXT,
    IncidentTypeCategory TEXT,
    IncidentTypeKind TEXT,
    InitialLatitude TEXT,  -- todo: convert to DOUBLE PRECISION,
    InitialLongitude TEXT,  -- todo: convert to DOUBLE PRECISION,
    InitialResponseAcres TEXT,  -- todo: convert to DOUBLE PRECISION,
    InitialResponseDateTime TEXT,  -- todo: convert to timestamp,
    IrwinID TEXT,
    IsFireCauseInvestigated TEXT,  -- todo: convert to INTEGER,
    IsFireCodeRequested TEXT,  -- todo: convert to INTEGER,
    IsFSAssisted TEXT,  -- todo: convert to INTEGER,
    IsMultiJurisdictional TEXT,  -- todo: convert to INTEGER,
    IsQuarantined TEXT,  -- todo: convert to INTEGER,
    IsReimbursable TEXT,  -- todo: convert to INTEGER,
    IsTrespass TEXT,  -- todo: convert to INTEGER,
    IsUnifiedCommand TEXT,  -- todo: convert to INTEGER,
    IsValid TEXT,  -- todo: convert to INTEGER,
    LocalIncidentIdentifier TEXT,
    ModifiedBySystem TEXT,
    PercentContained TEXT,  -- todo: convert to INTEGER,
    PercentPerimeterToBeContained TEXT,  -- todo: convert to INTEGER,
    POOCity TEXT,
    POOCounty TEXT,
    POODispatchCenterID TEXT,
    POOFips TEXT,
    POOJurisdictionalAgency TEXT,
    POOJurisdictionalUnit TEXT,
    POOJurisdictionalUnitParentUnit TEXT,
    POOLandownerCategory TEXT,
    POOLandownerKind TEXT,
    POOLegalDescPrincipalMeridian TEXT,
    POOLegalDescQtr TEXT,
    POOLegalDescQtrQtr TEXT,
    POOLegalDescRange TEXT,
    POOLegalDescSection TEXT,
    POOLegalDescTownship TEXT,
    POOPredictiveServiceAreaID TEXT,
    POOProtectingAgency TEXT,
    POOProtectingUnit TEXT,
    POOState TEXT,
    PredominantFuelGroup TEXT,
    PredominantFuelModel TEXT,
    PrimaryFuelModel TEXT,
    SecondaryFuelModel TEXT,
    TotalIncidentPersonnel TEXT,  -- todo: convert to INTEGER,
    UniqueFireIdentifier TEXT,
    WFDSSDecisionStatus TEXT,
    EstimatedFinalCost TEXT,  -- todo: convert to DOUBLE PRECISION,
    OrganizationalAssessment TEXT,
    StrategicDecisionPublishDate TEXT,  -- todo: convert to timestamp,
    CreatedOnDateTime_dt TEXT,  -- todo: convert to timestamp,
    ModifiedOnDateTime_dt TEXT,  -- todo: convert to timestamp,
    IsCpxChild TEXT,  -- todo: convert to INTEGER,
    CpxName TEXT,
    CpxID TEXT,
    SourceGlobalID TEXT,
    GlobalID TEXT,
    IncidentComplexityLevel TEXT,
    x TEXT,  -- todo: convert to DOUBLE PRECISION,
    y TEXT  -- todo: convert to DOUBLE PRECISION
)